### ISSUE TITLE
Jupyter Kernel dies on error

### ISSUE THREAD

**Issue by p-fruck** [piuswalter/Chess-AI#43]
The purpose of this issue is to track down and document our current issues with `juypter-execute`.

## Error handling issues

As shown in [this action](https://github.com/piuswalter/Chess-AI/actions/runs/1846883173), we are facing issues when it comes to error handling with jupyter notebook. The execution of the given notebook fails because of an error in our code (`AttributeError: 'NoneType' object has no attribute 'promotion'`). 

The direct output of `jupyter-execute` is the following:

```log
2022-02-15T14:13:14.7400915Z [NbClientApp] msg_type: status
2022-02-15T14:13:14.7401448Z [NbClientApp] content: {'execution_state': 'idle'}
2022-02-15T14:13:17.2453367Z [NbClientApp] Kernel is taking too long to finish, terminating
```

However the pipeline has passed for some reason. Seems like `jupyter-execute` returned an exit code of zero even though it has obviously failed.

## Reproduce
The game crashes when `Exercise04AI` (white player) plays against `Exercise03AI` (black player) with seed 13 and depth 3 on the third repetition.

To reproduce this scenario, simply execute
```sh
players=Exercise03AI opponents=Exercise04AI seed=13 repetitions=3 depth=3 jupyter-execute src/Statistics.ipynb
```
(Does not work on windows :P)

Also you might want to add the `--NbClientApp.log_level=<DEBUG|NFO|WARN|ERROR|CRITICAL>` flag to the command.

## ToDo
- [x] Fix our bug in the code
- [x] Make pipeline fail on error
- [x] Improve error logging in pipelines (only display relevant error messages if possible)

**Comment by antonplagemann** [comment]
There is antohter issue with died kernel at [this pipeline run](https://github.com/piuswalter/Chess-AI/runs/5207640673?check_suite_focus=true).
Log snippet:
```
[NbClientApp] Executing delayed clear_output
[NbClientApp] msg_type: stream
[NbClientApp] content: {'name': 'stdout', 'text': 'Current state (White): State.MIDDLE_GAME\n\n'}
[NbClientApp] ERROR | Kernel died while waiting for execute reply.
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nbclient/client.py", line 730, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nbclient/util.py", line 96, in ensure_async
    result = await obj
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/jupyter_client/channels.py", line 224, in get_msg
    ready = await self.socket.poll(timeout)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nbclient/client.py", line 949, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.2/x64/bin/jupyter-execute", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/jupyter_core/application.py", line 264, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.initialize(argv)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/traitlets/config/application.py", line 88, in inner
    return method(app, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nbclient/cli.py", line 113, in initialize
    [self.run_notebook(path) for path in self.notebooks]
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nbclient/cli.py", line 113, in <listcomp>
    [self.run_notebook(path) for path in self.notebooks]
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nbclient/cli.py", line 154, in run_notebook
    client.execute()
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nbclient/client.py", line 953, in async_execute_cell
    raise DeadKernelError("Kernel died")
nbclient.exceptions.DeadKernelError: Kernel died
```

The strange thing is that the GitHub Actions log just says `Running statistics notebook` as the last line and the step has an exit code of 0.

**Comment by antonplagemann** [comment]
@p-fruck 
On the last pipeline runs (commit 5307aff2ceddb00d17e8f03c47de78b4e300f04e, [example run here](https://github.com/piuswalter/Chess-AI/actions/runs/1857341483)) all 6 pipelines failed with `Kernel died` :-(
What's remarkable is that 5/6 pipelines failed together after **exact** `1h 50m` of running time.
Also 5/6 pipelines failed while playing with `Exercise04AI` as either black or white player (or both).
Therefore I suspect the memoization cache getting too big.
To Dos:
- [ ] Make pipelines fail on `Kernel died` error
- [ ] Discuss if we should change cache to player-specific (instance variable) instead of run-specific (static class variable). That would decrease the cache size but naturally also reduce cache hits.
- [ ] Log resource consumption during pipeline runs the confirm the error cause

**Comment by p-fruck** [comment]
@antonplagemann I've implemented some simple memory statistics in 9a6ed5ad7927d64dc1511621871ea4a84e9accc2, could you re-run the pipelines with the specified environment parameters? Also, dc4615bc9cc3f3fb6d19cdeac0cc9f94eada4872 should make the pipeline crash on kernel died events

**Comment by antonplagemann** [comment]
@p-fruck 
Tasks failed successfully ;-)
[➡](https://github.com/piuswalter/Chess-AI/actions)

**Comment by p-fruck** [comment]
That's what I've expected. Did you have a look at the logs already?
```
Cache size: 5.000083923339844 MiB 
Cache size: 10.000091552734375 MiB 
Cache size: 20.000083923339844 MiB 
Cache size: 40.000091552734375 MiB 
Cache size: 80.00008392333984 MiB 
Cache size: 160.00009155273438 MiB 
Cache size: 320.00008392333984 MiB 
Cache size: 640.0000915527344 MiB 
```
The kernel died somewhere during the journey of reaching > 1 GB of memory consumption (that is for our cache only). Guess we have to do some serious optimization...

**Comment by antonplagemann** [comment]
@p-fruck 
Now, with instance limited cache, we have much less memory consumption:
```
Cache size: 5.000083923339844 MiB 
Cache size: 10.000091552734375 MiB 
Cache size: 20.000083923339844 MiB 
Cache size: 40.000091552734375 MiB 
Cache size: 80.00008392333984 MiB 
Cache size: 160.00009155273438 MiB 
```
Also all pipelines passed successfully. I think that we then have found the bug and should switch to an instance cache. Surprisingly I could not find a significant loss in speed when compared to class-wide caching. I found no significant benefit of memoization at all 😅 (but also no significant deficit, which is definitely an improvement 😊 ). Maybe we should discuss if we can further improve the cache key.
